server:
  port: 8080

spring:
  application:
    name: redis-lock
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 5000
    jedis:
      pool:
        max-wait: -1
        min-idle: 0
        max-idle: 8

redis:
  default:
    expireTime: 3000